### ISSUE TITLE
How can we best quickly add new settings?

### ISSUE THREAD

**Issue by davidonelson** [DynEntTech/connectedwarehouse#15]
ASSIGNMENT:
Please research and confirm we can store data, like settings, on the local device.  

NOTES:

Settings are currently stored in CB database columns. In order to add a new settings and store them in the current manner,, changes are needed outside of this open source (CB table, CB stored procedures, CB POS web service, which are not open source).

If we can store new settings on the local device, then I suggest we proceed with the addition of new settings as follows:
- Add the new settings with the note "(stored locally)" so it is clear to all the settings is local to the device
- Proceed to use the new setting in the programming of the Warehouse client
- Submit a request to CB to add the new settling database column and web service XML element to the next release of CB
- After the new setting becomes available in CB, switch the code from storing the settings locally to storing the setting in the CB database

Related links:
https://github.com/connectedbusiness/connectedwarehouse/issues/19
Dynenttech https://github.com/DynEntTech/connectedwarehouse/issues/4

**Comment by Surinderkaur329** [comment]
**Reply**:
-----------------------------------------------------------------------------------------------

Settings are currently stored in CB database columns. In order to add a new settings and store them in the current manner,, changes are needed outside of this open source (CB table, CB stored procedures, CB POS web service, which are not open source).

If we can store new settings on the local device, then I suggest we proceed with the addition of new settings as follows:

Q:  Add the new settings with the note "(stored locally)" so it is clear to all the settings is local to the device.

**Ans: Yes we can store the setting in locally (only device where app installed) with the notes Stored locally).**

Q: Proceed to use the new setting in the programming of the Warehouse client.

**Ans: Yes new setting will be proceed with warehouse client locally with the app.**

Q: Submit a request to CB to add the new settling database column and web service XML element to the next release of CB.

**Ans:  Yes for this we need to create new database column for the new setting.  But before that we can test all new setting on our local end .
After we done successfully test we can do that to add new column in the database and save the setting whenever every user use that setting .
In this way we can easily do that.**

After the new setting becomes available in CB, switch the code from storing the settings locally to storing the setting in the CB database.

**Ans: Yes its very easy to use that .**
